README.md

This PR is part of react-native-community/.github#45
Added LeanCore extracted badge in README.

Add LeanCore Extracted Badge

---

README.md
ios/RNCSegmentedControl.m
ios/RNCSegmentedControl.xcodeproj/project.pbxproj
ios/RNCSegmentedControlManager.m

Following the issue in #43 I am adding this PR in order to fix the compilation. Basically I:
* Added missing files to the XCode project (the `RNCSegmentedControlManager.*` files were not added)
* Changed the `React` imports in the project from `#import "RCTLibrary.h"` to `#import <React/RCTLibrary.h>`
* Added a line in the documentation to let users know that they should link this library to their project to make it work. 
**NOTE:** I only added a link to the manually linking instructions, but this should be done in a better way (for instance by doing a `pod install` or something like this). I don't know very  much how installed libraries can be added to the Podfile of the root project when being installed so I did not add that change here, but this would be a nice enhancement to this PR. …

Fix broken compilation in v1.1.0

---

README.md
package.json

Fixed url from `react-native-segmented-control` to `segmented-control`, due to renaming of the repo

chore: fix url

---

index.d.ts

There's no type information for `activeTextColor` property which was added recently in https://github.com/react-native-community/segmented-control/pull/50
I don't really have a test plan for this fix. For now it simply works.

Add activeTextColor to index.d.ts

---

js/RNCSegmentedControlNativeComponent.js

motivation: `ColorValue` is the intended flow type for color props
I didn't actually test this, but the definition of ColorValue is `type ColorValue = null | string;` so I don't see why it would break anything

use ColorValue for color props

---

index.d.ts
ios/RNCSegmentedControl.m
ios/RNCSegmentedControlManager.m

Adds the feature to override control's theme appearance on iOS 13+

Add appearance feature

---

README.md

Modified README
Added a screenshot of android implementation
Changed name of component in example from SegmentedControlIOS to SegmentedControl (no breaking change, as this is a default export)

docs: add screenshot of android implementation

---

ios/RNCSegmentedControl.m
js/SegmentedControl.js
js/SegmentedControlTab.js
package.json

Fixing issue #80 
Add `fontSize` to the segmented control and check that boldface is applied only to the selected tab.

fix: ios: Not selected tab gets bold face when setting fontSize #80

---

example/App.js
ios/RNCSegmentedControl.m

combining fontSize, textColor, tintColor and activeTextColor lead to some styles not working.
This PR fixes the problem
Tested on iPhone Simulator

fix: allow combining attributes

---

ios/RNCSegmentedControlManager.m

Fixes: https://github.com/react-native-community/segmented-control/issues/93
Use example with `fontStyle` and `activeFontStyle`

[iOS] fix activeFontStyle prop being override by fontStyle

---

js/SegmentedControl.js

I have a Fully RTL App when I press to next segment the Animation It goes the other way around
I import I18nManager then defined a variable to check if the app RTL or not and based on it, I change `segmentWidth` to negative if true, else i return `segmentWidth` 
**Before**
**After**

Fix Animation Active segmant width in RTL

---

react-native-segmented-control.podspec

Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for native modules on iOS. This change requires to React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.

fix: Xcode 12 compatibility

---

README.md
js/SegmentedControlTab.js
js/types.js

Added custom font styling for font-weight to fix issue #130
I Added fontWeight property on fontStyle & activeFontStyle props. Here is the example:
```javascript
<SegmentedControl
values={['One', 'Two']}
selectedIndex={this.state.selectedIndex}
onChange={(event) => {
this.setState({selectedIndex: event.nativeEvent.selectedSegmentIndex});
}}
activeFontStyle={{
fontWeight: '500'
}}
fontStyle={{
fontWeight: '200'
}}
/>
```

feat: Add Custom Font Weight Styling

---

index.d.ts

Adding the `fontWeight` property for the font style in the TypeScript declaration, along with some minor update.
This new property has been added recently but the TypeScript type hasn't been updated.

style: TypeScript declaration fixes

---

.github/workflows/public.yml
package.json

feat: setup auto deploy

---

README.md
index.d.ts
js/SegmentedControl.ios.js
js/SegmentedControl.js
js/SegmentedControlTab.js
js/types.js

Based on issue: https://github.com/react-native-segmented-control/segmented-control/issues/216
There is a problem on how react-native-web handles the transformation when it comes to flex, absolute and relative positioning. Basically Text container (TouchableOpacity in our case) is not expanding to full size.
Thus  I opened API for TouchableOpacity styles. This will allow users to change actual padding of the clickable area. No backwards compat introduced, very small code change but this will grant devs more power when it comes to styling.
Since library uses different components for IOS and android:
- in ios we can prepend styles to RNCSegmentedControlNativeComponent,
- in android we can add it to the TouchableOpacity
I dont see any tests in the library so here is my video: …

Allow touchable to be stylable

---

.github/workflows/ci.yml

use node v12 for ci as 10 is eol

chore: fix node version used in ci

---

example/ios/Podfile
example/ios/Podfile.lock

Fix iOS CI

---

index.d.ts

Updating to react native 0.71, TypeScript errors on this library. The utility type `Constructor` is private in latest typings. Using this export degrades to `any` type.
`JSX element class does not support attributes because it does not have a 'props' property.`
`npx tsc` runs clean after making this change on a RN 0.71 app.

fix(types): utility type removed from RN 0.71

---

.github/workflows/ci.yml

Will fix Android CI in a different PR

Add Check for Node 16

---

ios/RNCSegmentedControl.m

I noticed a bug where the text color of the component would revert back to its default value after changing the tintColor. This behavior is not ideal as it disrupts the user experience and makes the component less flexible for dynamic UI changes. My motivation for making this change is to fix this issue and improve the component's reliability.
related with https://github.com/react-native-segmented-control/segmented-control/issues/641
Manually tested the component on multiple devices running iOS 13 and above.
Changed the tintColor dynamically after the component had rendered to verify that the text color does not revert to its default value.
Checked other properties to ensure they are not affected by this change.

fix:Fix text color reverting to default after changing tintColor

---

js/SegmentedControl.js
js/SegmentedControlTab.js

Implements the suggestions given in #109.
This resembles the mechanics of the native iOS UISegmentedControl but then for Android.

feat: better accessibility hinting

---

react-native-segmented-control.podspec

Add visionOS to support to the podspec. No big repo update to 0.73 this time. Maybe as a followup. 
CI should pass

feat: Add visionOS support to podspec

---

js/SegmentedControl.js

Recreate #731 to fix merge conflicts.
CI should pass. Also assuming fix works from the screenshots of the earlier version.

fix: content not visible on js version (redo)

---

ios/RNCSegmentedControl.h
ios/RNCSegmentedControl.m
ios/RNCSegmentedControlManager.m
js/SegmentedControl.js
js/SegmentedControlTab.js
js/types.js

Thanks for creating this owesome library. There is a small concern, even though it is very helpful. There is no feature for sending testIDs for individual segment buttons/components. I've done with the implementation of this feature for both Android and iOS and creating this PR. I hope this could get merged quickly, as we are in need of this change.
Send an array of identifiers into testIDS and check if they are reflecting or not. 
ex:
<SegmentController 
{...props}
testIDS={["option1", "option2", "option3"]}
/>

Added testIDS prop which can be used to pass testID to individual segment buttons

---

js/SegmentedControlTab.js

Thank you very much for merging the previous PR, and I would kindly request that you please merge this one as we need the accessibility locator also, and it's useful for many of the users.
You can just check if the locator is reflecting as accessibility-id in Appium Inspector.

added accessibility id as a locator

---

README.md
index.d.ts
js/SegmentedControl.js
js/types.js

Include fix in #515 with conflicts resolved

feat: Allow the slider component to be styled
