react-native-segmented-control/segmented-control

- react-native-segmented-control.podspec
> Update repository url in podspec

- README.md
The screenshot in the README doesn't have to be full size.
Also, fixed a typo naming uppercase.
> Fix README's screenshot

- package.json
> Rename repository URLs

- .circleci/config.yml
- index.d.ts
- package.json
- tsconfig.json
Added tsc check to ci to verify that there are no syntax errors in `index.d.ts`
yarn tsc
> Add tsc check to CI

- ios/RNCSegmentedControl.h
- ios/RNCSegmentedControl.m
- ios/RNCSegmentedControl.xcodeproj/project.pbxproj
- ios/RNCSegmentedControlManager.h
- ios/RNCSegmentedControlManager.m
- js/RNCSegmentedControlNativeComponent.js
- js/SegmentedControlIOS.ios.js
Fixes #15 
Renamed RCTSegmentedControl to RNCSegmentedControl
Tested with ios simulator
| iPhone 11 |
| --- |
| <img src="https://user-images.githubusercontent.com/6936373/71769659-252c0400-2f67-11ea-9082-dec747da290d.png" width="320" /> |
> Rename from RCTSegmentedControl to RNCSegmentedControl

- ios/RNCSegmentedControl.h
- ios/RNCSegmentedControl.m
motivation: the array does not appear to be really used.
My app doesn't do anything complicated with segmented control - just display some segments and listen to onChange. This still seems to work.
> remove unneeded values array

- README.md
Added Reference for Props in the README, similar to how it's done in `reactnative.dev`
This only changes the README
> Add Prop Reference in README

- index.d.ts
- ios/RNCSegmentedControl.m
- ios/RNCSegmentedControlManager.m
- js/RNCSegmentedControlNativeComponent.js
Continuing from #61 
Adding appearance to flowtype as well
Tested on iOS simulator
flow passes
> feat: add Appearance Props

- README.md
Adding Appearance props in README
> Add Apperance Props in README

- index.d.ts
- js/RNCSegmentedControlNativeComponent.js
- js/SegmentedControlIOS.android.js
- js/SegmentedControlIOS.ios.js
- js/SegmentedControlTab.js
- js/types.js
- package.json
Created a Android version of segmentedControl component written in js
What's not implemented: moment support, gesture support.
Works on android emulator
test passes
> feat: add SegmentedControl for android

- README.md
Added screenshot of web implementation in README
> docs: Add screenshot for web

- js/SegmentedControl.js
- js/SegmentedControlTab.js
Added animation to selection change on Android and Web
Just change selection few times on Android & Web
> feat: Animate segment selection on Android

- js/SegmentedControl.js
Applied style to match the looks of iOS 13 Segmented Control
Tested on Android Emulator and Web
> chore: apply style to match iOS 13 Segmented Control

- index.d.ts
- ios/RNCSegmentedControl.m
- ios/RNCSegmentedControlManager.m
Adds fontFamily support on iOS
Tested on iOS simulator
> feat: Adds fontFamily support on iOS, Closes #85

- README.md
Add documentation of `fontStyle` and `activeFontStyle` in Readme
> docs: add props detail for fontStyles

- package.json
- yarn.lock
Updating devDependencies for security update
> chore: update lint config

- js/SegmentedControl.js
> Fix spacing issue on android

- package.json
- yarn.lock
bump @expo/webpack-config to address security alert
web example works
> bump @expo/webpack-config

- README.md
- package.json
Fixes #141 
Added support version in README, and modified peer dependency versions
> chore: update peerDependency version

- .flowconfig
- package.json
- yarn.lock
> chore: update flowtype

- CONTRIBUTING.md
- README.md
- package.json
- react-native-segmented-control.podspec
part of https://github.com/react-native-community/discussions-and-proposals/issues/330
moving this package to `@react-native-segmented-control/segmented-control`
> feat: migrate to different namespace

- js/SegmentedControlTab.js
A small change, accessibilityState added so that the selected tab is specified out loud for TalkBack on android.
> feat: added accesibility for selected tab

- package.json
> docs: fix url of repository

- .github/workflows/ci.yml
- .github/workflows/public.yml
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
> Update Node Version for CI

- .eslintrc.js
> Fixed "Delete `␍`eslintprettier/prettier" Error

- .github/workflows/publish.yml
> fix: publish ci

- js/SegmentedControl.js
> fix: fix the slider text for android when selected

- js/SegmentedControlTab.js
> feat: add testid for tab

- .github/workflows/ci.yml
> feat: update to node 20
